variable "region" {}
variable "instance_type" {}
variable "ami" {}
variable "PATH_TO_PUBLIC_KEY" {}
variable "PATH_TO_PRIVATE_KEY" {}
variable "INSTANCE_USERNAME" {}
variable "cidr_block" {}
variable "project_name" {}
variable "public_subnet1_cidr_block" {}
variable "public_subnet2_cidr_block" {}
variable "private_subnet1_cidr_block" {}
variable "private_subnet2_cidr_block" {}